### ISSUE TITLE
[Improvement] Listen for signals

### ISSUE THREAD

**Issue by yoeriboven** [mateusjatenee/crypto-tracker#2]
I was just writing an Artisan command and came across this [article](https://laravel-news.com/handling-signals-in-laravel-console-commands).

You might want to check it out to replace `listenForSignals()` in [`FetchCoinsPrices`](https://github.com/mateusjatenee/crypto-tracker/blob/master/app/Console/Commands/FetchCoinsPrices.php)

**Comment by mateusjatenee** [comment]
Cool stuff! Any chance you could PR this? 😃

**Comment by yoeriboven** [comment]
Sorry, kinda busy.

It was more to show you Laravel has native support for this. :wink:

**Comment by mateusjatenee** [comment]
all good, thanks
